# Change these first
owner: BlackstoneStudio # Your GitHub username
repo: Blackstone-Status # Your Github repository name

# Add your sites here
sites:
  - name: Website
    url: https://www.blackstone.studio
  - name: App
    url: https://app.blackstone.studio
  - name: API
    url: https://api.blackstone.studio


status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.blackstone.studio
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Blackstone Studio Status
  introTitle: "*Setvices Uptime Status"
  introMessage: This is a sample status page which uses **real-time** data from our [Github repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Contact
      href: https://blackstone.studio/contact/

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
